##########
# BASE   #
##########

install_git: false


########
# DB   #
########

create_db: true
create_db_user: true
db_host: test
db_port: 3306
db_name: test
db_user: test
db_pass: test


########
# USER #
########

username: tarun
password: InuZ6/HkJkYOA
public_key: ~/.ssh/id_rsa.pub
sftp_user: 
server_hostname: 192.168.1.2
webserver_user: 
webserver_group: 

##########
# APACHE #
########## 



