---
- hosts: vms
  # user: vagrant
  become: yes
  roles:
    # - base
    # - user
    # - database
    - {name: nginx, tags: nginx}
    # - php-fpm
    # - app
    # 
    # - apache
    # - ufw
    # - ssh
    # - mariadb
    # - magento
    # - git-sync
    - {name: gitlab, tags: gitlab}