---
- hosts: vms
  # user: vagrant
  become: yes
  roles:
    # - base
    # - user
    # - database
    - nginx
    # - php-fpm
    # - app
    # 
    # - apache
    # - ufw
    # - ssh
    # - mariadb
    - magento
    # - git-sync