---
- hosts: vms
  # user: vagrant
  become: yes
  roles:
    # - base
    # - user
    - {name: database, tags: mysql}
    - {name: nginx, tags: nginx}
    - {name: php-fpm, tags: php}
    # - app
    # 
    # - apache
    # - ufw
    # - ssh
    # - mariadb
    # - magento
    # - git-sync
    # - {name: gitlab, tags: gitlab}