---
# This playbook will install mysql and create db user and give permissions.

- name: Install Mysql package
  apt:
   name: "{{ item }}"
   state: installed
  # when: create_db
  with_items:
   - mysql-server
   - python-mysqldb
   - libmysqlclient-dev
   # - libselinux-python
   # - libsemanage-python
  notify:
  - start mysql

# - name: Configure SELinux to start mysql on any port
#   seboolean: name=mysql_connect_any state=true persistent=yes
#   when: sestatus.rc != 0

# - name: Create Mysql configuration file
#   template: src=my.cnf.j2 dest=/etc/my.cnf
#   notify:
#   - restart mysql



# - name: insert iptables rule
#   lineinfile: dest=/etc/sysconfig/iptables state=present regexp="{{ mysql_port }}"
#               insertafter="^:OUTPUT " line="-A INPUT -p tcp  --dport {{ mysql_port }} -j  ACCEPT"
#   notify: restart iptables

- name: Create Application Database
  mysql_db:
   name: "{{ db_name }}"
   state: present
  when: create_db

- name: Create Application DB User
  mysql_user: name="{{ db_user }}" password="{{ db_pass }}" priv=*.*:ALL host='%' state=present
  when: create_db_user