---
# - name: Upgrade packages
#   apt: upgrade=safe
  
- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
    # update_cache: yes
    force: yes
  with_items:
  - fail2ban
  - mcrypt
  # - ufw

- name: Installing git
  apt:
    name: "git-core"
    state: present
    force: yes
  when: install_git